# Generated by Django 4.2.1 on 2024-05-01 07:44

from django.db import migrations

def populate_classes(apps, schema_editor):
    MAX_CLASS = 12
    CLASS_CHOICES = [i for i in range(1,MAX_CLASS+1)]
    ClassName = apps.get_model('accounts', 'ClassName')
    for val in CLASS_CHOICES:
        ClassName.objects.create(name=val)

def populate_organisation_type(apps, schema_editor):
    ORGANISATION_TYPE = [ 'Central Government', 'State Government', 'Public Company', 'Private Company', 'NGO', 'Foreign' ]
    OrganisationType = apps.get_model('accounts', 'OrganisationType')
    for type in ORGANISATION_TYPE:
        OrganisationType.objects.create(name=type)

def populate_school_type(apps, schema_editor):
    SCHOOL_TYPE = [ 'Central Government Funded', 'State Government Funded',
                            'Public Company Funded', 'Private Company Funded', 'NGO Funded', 'Foreign Funded', 'Self-Funded']
    SchoolType = apps.get_model('accounts', 'SchoolType')
    for type in SCHOOL_TYPE:
        SchoolType.objects.create(name=type)

def populated_context(apps, schema_editor):
    CONTEXTS = [
        'organisation', 'state', 'district', 'city', 'school', 'class', 'section'
    ]
    Context = apps.get_model('accounts', 'Context')
    for val in CONTEXTS:
        Context.objects.create(name = val)

class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_classes), migrations.RunPython(populate_organisation_type), 
                  migrations.RunPython(populate_school_type)]
